name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Isometric commit calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # Language Plugin
          plugin_languages: yes
              
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: CV.tex
          working_directory: ..
          
